// Experiment MCP deployment (#575). The deployed Supabase function is a stub
// that imports the MCP from GitHub at one pinned commit, so deploying means
// pinning a new commit, and /health reports the commit it runs.
//
//   node web/scripts/mcp-deploy.mjs stub <commit> <workdir>
//       write <workdir>/supabase/functions/experiment-mcp/{index.ts,deno.json}
//   node web/scripts/mcp-deploy.mjs verify <commit>
//       wait until the live /health reports <commit>
//   node web/scripts/mcp-deploy.mjs status
//       print the live commit and whether the repository's MCP code differs from it

import { execFileSync } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";

export const MCP_REPOSITORY = "eliseofe/virtual-lab";
export const MCP_SLUG = "experiment-mcp";
export const MCP_SOURCE_PATH = "supabase/functions/experiment-mcp";
export const MCP_HEALTH_URL = "https://izdmmudfrmqhvlgepwes.supabase.co/functions/v1/experiment-mcp/health";

const COMMIT = /^[0-9a-f]{40}$/;

export function stubFiles(commit) {
  if (!COMMIT.test(commit)) throw new Error(`not a full commit id: ${commit}`);
  return {
    "index.ts": `// Deployment entrypoint pinned to commit ${commit}.\n// Generated by web/scripts/mcp-deploy.mjs; see docs/EXPERIMENT_MCP.md.\nimport "https://raw.githubusercontent.com/${MCP_REPOSITORY}/${commit}/${MCP_SOURCE_PATH}/index.ts";\n`,
    "deno.json": `${JSON.stringify({ compilerOptions: { lib: ["deno.window", "deno.ns"], strict: true }, imports: {} }, null, 2)}\n`,
  };
}

async function writeStub(commit, workdir) {
  const dir = path.join(workdir, "supabase", "functions", MCP_SLUG);
  await mkdir(dir, { recursive: true });
  for (const [name, content] of Object.entries(stubFiles(commit))) await writeFile(path.join(dir, name), content);
  console.log(`MCP stub pinned to ${commit} written to ${dir}`);
}

async function liveCommit() {
  const response = await fetch(MCP_HEALTH_URL, { headers: { accept: "application/json" } });
  if (!response.ok) throw new Error(`MCP /health answered ${response.status}`);
  const health = await response.json();
  return health.source_commit ?? null;
}

async function verify(commit) {
  let seen = null;
  for (let attempt = 0; attempt < 20; attempt += 1) {
    seen = await liveCommit().catch((error) => `error: ${error.message}`);
    if (seen === commit) {
      console.log(`Live MCP runs ${commit}.`);
      return;
    }
    await new Promise((resolve) => setTimeout(resolve, 6000));
  }
  throw new Error(`live MCP reports ${seen}, expected ${commit}`);
}

async function status() {
  const commit = await liveCommit();
  if (!commit) throw new Error("live MCP does not report its source commit");
  let differs;
  try {
    execFileSync("git", ["diff", "--quiet", commit, "HEAD", "--", MCP_SOURCE_PATH], { stdio: "ignore" });
    differs = false;
  } catch {
    differs = true;
  }
  console.log(differs ? `Live MCP runs ${commit}; the repository's MCP code has changed since — a deployment is due.` : `Live MCP runs ${commit}; the repository's MCP code is identical.`);
  if (differs) process.exitCode = 1;
}

const [command, ...args] = process.argv.slice(2);
if (command === "stub" && args.length === 2) await writeStub(args[0], args[1]);
else if (command === "verify" && args.length === 1) await verify(args[0]);
else if (command === "status") await status();
else if (command) {
  console.error("usage: mcp-deploy.mjs stub <commit> <workdir> | verify <commit> | status");
  process.exitCode = 2;
}
